/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_mainwindow (void);
GtkWidget* create_dialog_preferences (void);
GtkWidget* create_dialog_connect (void);
GtkWidget* create_dialog_azel_graph (void);
GtkWidget* create_dialog_dbedit (void);
GtkWidget* create_dialog_about (void);
