#!/bin/bash
# Script to install moontracker
#
if [ ! -x $PWD/moontracker ]; then
	$PWD/build
fi
whoami=`whoami`
if [ ! -x /usr/local/bin/moontracker ]; then
	if [ $whoami != "root" ]; then
		echo "Sorry, $whoami.  You need to be 'root' to install this program.  :-("
		echo "Please su to root and re-run the 'install' script again."
	else
		ln -s $PWD/moontracker /usr/local/bin/moontracker
	fi
fi

