.TH "fodtrack" "8" "0.1" "Luc Langehegermann" "LX2GT Sat tools"
.SH "NAME"
.LP 
fodtrack \- Driver for the fodtrack rotor interface
.SH "SYNTAX"
.LP 
fodtrack
.SH "DESCRIPTION"
.LP 
This program simulates an Easycom rotor interface. It read its configuration parameters from the file \fB/etc/fodtrack.conf\fR. It reads the headings in the form of \fBAZ10.0 EL45.0\fR and outputs it to an parallel port. When started it displays a small status text, creates the file \fB/tmp/fodtrackdevice\fR \- which contains the pseudo device used \- and goes into the background.

.SH "FILES"
.LP 
\fI/etc/fodtrack.conf\fP 
.br 
\fI/tmp/fodtrackdevice\fP 
.SH "EXAMPLES"
.LP 
To run this program type:
.LP 
fodtrack
.LP 
After that you can start predict with \fBpredict \-a `cat /tmp/fodtrackdevice`\fR and you will be able to turn your antennas in predict single track using your fodtrack device
.SH "AUTHORS"
.LP 
Luc Langehegermann <luc@1409.org>
.SH "SEE ALSO"
.LP 
fodtrack.conf(5)
