#!/bin/bash
# Script to install geosat
#
if [ ! -x $PWD/geosat ]; then
	$PWD/build
fi
whoami=`whoami`
if [ ! -x /usr/local/bin/geosat ]; then
	if [ $whoami != "root" ]; then
		echo "Sorry, $whoami.  You need to be 'root' to install this program.  :-("
		echo "Please su to root and re-run the 'install' script again."
	else
		ln -s $PWD/geosat /usr/local/bin/geosat
	fi
fi

