#!/bin/sh
# Script to compile and install 'map'
#
echo "Compiling 'map'.  If a compilation error occurs, please"
echo "edit the 'build' script according to the location of your"
echo "X11 and xforms libraries."
echo
#
# Select one of the following lines depending on your specific directory
# and include file paths.  The first line works fine under Slackware.
#
cc -Wall -O3 -s -o map map.c map_cb.c map_main.c -L/usr/X11R6/lib -lforms -lX11 -lm
#cc -Wall -O3 -s -o map map.c map_cb.c map_main.c -lforms -lX11 -lm
echo "Done!"
whoami=`whoami`
if [ ! -x /usr/local/bin/map ]; then
	if [ $whoami != "root" ]; then
		echo "Sorry, $whoami.  You need to be 'root' to install this program.  :-("
		echo "Please su to root and re-run this script again."
	else
		ln -s $PWD/map /usr/local/bin/map
	fi
fi

