#!/bin/sh
# This script builds the man page, pdf, postscript, html,
# and text documentation from the groff source "predict.man".
echo -n "Creating postscript file... "
groff -T ps -man predict.man > ../postscript/predict.ps
echo
echo -n "Creating man page... "
groff -T ascii -man predict.man > predict.1
echo
echo -n "Creating text file... "
ul -t dumb predict.1 > ../text/predict.txt
echo
#echo -n "Creating HTML file... "
#groff -T html -man predict.man > ../html/predict.html
#echo
echo -n "Creating pdf file... "
ps2pdf ../postscript/predict.ps ../pdf/predict.pdf
echo
echo "Done!"
